### ISSUE TITLE
Raspberry Pi (arm64) shows two metrics only

### ISSUE THREAD

**Issue by converge** [nshttpd/mikrotik-exporter#111]
hi,

I was using the regular Dockerfile and I could read metrics by the endpoint: http://localhost:9436/metrics

since I started using a Raspberry PI and the [arm64](https://github.com/nshttpd/mikrotik-exporter/blob/master/Dockerfile.arm64) Dockerfile via `nshttpd/mikrotik-exporter-linux-arm64:1.0.11` Im able to reach the endpoint, but there is just two metrics:

```
mikrotik_scrape_collector_duration_seconds{device="device-name"} 0.001479678
mikrotik_scrape_collector_success{device="device-name"} 0
```

I tried many things like:
- overriding the Dockerfile entrypoint, and running the main/binary manually (setting the config file and also setting environment values like -with-dhcp, with-routes, etc`

Any idea what could be wrong?

**Comment by nshttpd** [comment]
Did the container spit out any logs to STDOUT/STDERR? 

My first guess is that the container network can't reach the network that the device is on. That should spit out a timeout error I believe. Something like a `docker logs mikrotik-exporter` if you named the container upon startup should have that. 

If that's not it, post up what the config looks like or the command line. In the examples directory there is a docker-compose example that might possibly help. I've got it running on a pi at the moment, but not in docker that I'll try to switch out here in a bit to see if it works for me.

**Comment by converge** [comment]
hey, sorry , that was actually my bad. Mikrotik was blocking the IP address from use the API endpoint/service to collect data.
