### ISSUE TITLE
`insecureTLS` is hardcoded to `true`.

### ISSUE THREAD

**Issue by devon-mar** [nshttpd/mikrotik-exporter#113]
The insecure flag is passed to `WithTLS`: https://github.com/nshttpd/mikrotik-exporter/blob/6f53244308040a85a37798472a82a7d6d7a65821/main.go#L271

but never actually used:
https://github.com/nshttpd/mikrotik-exporter/blob/6f53244308040a85a37798472a82a7d6d7a65821/collector/collector.go#L164-L169

**Comment by nshttpd** [comment]
Thanks.
