### ISSUE TITLE
Traffic rate don't match

### ISSUE THREAD

**Issue by cis2131** [nshttpd/mikrotik-exporter#115]
I have added 2 routers to the exporter. but the traffic on all the interfaces don't match real throughput.

E.g 5,5 Gigabit gives around 688 Mbit/s in grafana dashboard.

What am I doing wrong?.

**Comment by SocialQuantumLtd** [comment]
Take it easier) Exporter gives out bytes instead of bits.

**Comment by nshttpd** [comment]
Yup, the bytes vs bits thing.
