### ISSUE TITLE
Arm docker images.

### ISSUE THREAD

**Issue by ananthb** [nshttpd/mikrotik-exporter#121]
Could Arm (armhf & arm64) docker images be added to docker hub? I'm ready to contribute to make this happen.

**Comment by nshttpd** [comment]
They are there in a separate ARM repo.(https://hub.docker.com/repository/docker/nshttpd/mikrotik-exporter-linux-arm64) at least for arm64. Somewhere in a tab or saved I have a bunch of docs on trying to get the multi-arch stuff working in a single repo.

**Comment by ananthb** [comment]
This PR might be useful here: https://github.com/nshttpd/mikrotik-exporter/pull/67. The multi stage build pattern makes it easier to use `docker buildx` to build multiplatform images.

Thanks for the arm images!

**Comment by ananthb** [comment]
@nshttpd I'm getting a manifest unknown error with that repository.

**Comment by cheahjs** [comment]
I wrote https://github.com/cheahjs/mikrotik-exporter/pull/1/files for myself for building x86/ARM/ARM64 Docker images on GitHub Actions
