### ISSUE TITLE
./main.go:141:25: cannot use nc

### ISSUE THREAD

**Issue by f3rr** [nshttpd/mikrotik-exporter#16]
I cannot compile
trying in ubuntu docker container

```
root@595d2699e46a:/mikrotik-exporter# GOOS=linux GOARCH=amd64 go build .
# _/mikrotik-exporter
./main.go:141:25: cannot use nc (type "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.Register:
	"github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
root@595d2699e46a:/mikrotik-exporter# 

```

**Comment by royolsen** [comment]
I could not get the solution above to work for me. 

```
[root@willow mikrotik-exporter]# rm -rf $GOPATH/src/*
[root@willow mikrotik-exporter]# go get -d .
[root@willow mikrotik-exporter]# go build .
# _/opt/go/mikrotik-exporter
./main.go:141:25: cannot use nc (type "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.Register:
	"github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
```

**Comment by nshttpd** [comment]
What version of Go? I've got a branch for circleci builds that's been sitting here for a while. I'll try to see if I can get some free time to finish it and just provide binaries or docker images or both.

**Comment by royolsen** [comment]
Go 1.10.3 in my case. Is there a specific version I should rather use?

**Comment by f3rr** [comment]
same error here:
root@fc729cea88cb:/mikrotik-exporter# go version
go version go1.10.4 linux/amd64

root@fc729cea88cb:/mikrotik-exporter# GOOS=linux GOARCH=amd64 go get -d .
root@fc729cea88cb:/mikrotik-exporter# GOOS=linux GOARCH=amd64 go build . 
# _/mikrotik-exporter
./main.go:141:25: cannot use nc (type "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.Register:
	"github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Collector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/nshttpd/mikrotik-exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
root@fc729cea88cb:/mikrotik-exporter#

**Comment by nshttpd** [comment]
I've got 1.10.3 also. Just did a `go get` update for all the prometheus clients to see if it's some weird conflict between vendor and $GOPATH .. still compiles without an error. I can't seem to reproduce it at the moment.

**Comment by nshttpd** [comment]
Even doing something like :

`docker run -ti -v $GOPATH:/go  golang:1.10-stretch bash`

to build it on ubuntu and not a Mac laptop doesn't error. For those that are having issues can you remove the `$GOPATH/src/github.com/prometheus/*` and see if that solves the problem?

**Comment by royolsen** [comment]
So, apparently the vendor folder is ignored if you are not working within the confinement of the GOPATH and it's specifications. See https://github.com/golang/go/issues/14566

I originally cloned to `/opt/mikrotik-exporter`, which caused the issue

The solution was to move the project folder to `$GOPATH/github.com/nshttpd/mikrotik-exporter` and build from there. 

So, a working approach for a Go newbie like myself would be

```
export GOPATH=~/go
mkdir -p $GOPATH/src/github.com/nshttpd
cd $GOPATH/src/github.com/nshttpd
git clone https://github.com/nshttpd/mikrotik-exporter.git
cd mikrotik-exporter
go build
```
This should result in a working binary at `~/go/src/github.com/nshttpd/mikrotik-exporter/mikrotik-exporter`

**Comment by f3rr** [comment]
i can confirm solution from royolsen is working
i did:
`docker run -it --rm ubuntu bash`
than
`apt update
apt install -y git golang-go
export GOPATH=~/go
mkdir -p $GOPATH/src/github.com/nshttpd
cd $GOPATH/src/github.com/nshttpd
git clone https://github.com/nshttpd/mikrotik-exporter.git
cd mikrotik-exporter
go build
`

and SCP out the binary from container
