### ISSUE TITLE
collect firmware version

### ISSUE THREAD

**Issue by kaihendry** [nshttpd/mikrotik-exporter#17]
https://www.reddit.com/r/mikrotik/comments/9njy62/be_good_if_mikrotik_could_autoupdate_reliably/e7o0l8a/

**Comment by nshttpd** [comment]
you mean the data reported by  `/system/package/getall`  ?

**Comment by nshttpd** [comment]
@kaihendry it may not be the firmware data we want, but it's the firmware data we need.

The 1.0.12-DEVEL version (if using containers) will have it if you enable the `firmware` collector.
