### ISSUE TITLE
Docker Hub Image

### ISSUE THREAD

**Issue by prologic** [nshttpd/mikrotik-exporter#28]
Please provide an automated build on the Docker Hub :)

**Comment by nshttpd** [comment]
Thanks for the PR. Let me see if I can do it all on the CircleCI side from the binaries that are already built and just start packaging them into containers for Docker Hub.

**Comment by nshttpd** [comment]
1.0.3 should be out on Docker Hub now and built and pushed with ever release now. Let me know if that doesn't work.

**Comment by prologic** [comment]
So you're not going to merge the multi-stage Dockerfile build?

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
