### ISSUE TITLE
How collect  tx/rx per time?

### ISSUE THREAD

**Issue by zakabluk** [nshttpd/mikrotik-exporter#33]
Hi! I launched mikrotik-exorter as result I have of common rx/tx data. But I want see rx/tx per time. My canal bandwidth in this time or late, because I can see it's information by mikrotik web interface.

**Comment by TitinDev** [comment]
Interested too, do you know if we can calculate it?

**Comment by zakabluk** [comment]
I have nothing that I can tell you. I have stopped using my mikrotik exporter and use only web interface him.

**Comment by mikegleasonjr** [comment]
I guess this is more related to prometheus.

Prometheus holds the history of your data, you should query prometheus to have a graph for a particular time frame.

**Comment by nshttpd** [comment]
the mikrotik-exporter is meant to be used in conjunction with prometheus for the collecting and storage of the metrics. Just on it's own it's not going to be helpful to you.

**Comment by TitinDev** [comment]
It is enough just to add a call on the url: '/interface/monitor-traffic'

Result : https://j.titin.fr/gPm1cJl
