### ISSUE TITLE
Doesn't seem to work after updating to RouterOS v6.45.1

### ISSUE THREAD

**Issue by janost** [nshttpd/mikrotik-exporter#36]
After updating my router to RouterOS v6.45.1 the application no longer works. According to the router's log there's an authentication issue:
```
login failure for user prometheus from IP_ADDRESS via api
```

It might have something to do with the following changelog item:
```
 !) user - removed insecure password storage;
```

**Comment by nshttpd** [comment]
I haven't upgraded to that version yet. I'll do it when I get home and see what's what. Did you try just resetting/recreating the password? Not sure if they did an "to secure storage" in the upgrade process or just a `rm *` on the passwords that were sitting unsecure.

**Comment by janost** [comment]
I tried changing the password and recreating the user, unfortunately the problem still persists.

**Comment by nshttpd** [comment]
Ok, I'll check it out when I get home after ${DAYJOB} and see what the fix might be.

**Comment by mdyring** [comment]
Any help on this greatly appreciated :-)

Quoting from Mikrotik forum:
>>me to, but i have problem on api, i can connect with winbox, but i can't login with API ( wrong password ). why?
>Do you use new login style in API?
>https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by mdanidl** [comment]
Hey, apparently there's a PR in the routeros package, but it hasn't been merged yet
https://github.com/go-routeros/routeros/pull/5/files

**Comment by nshttpd** [comment]
@janost can you pull 1.0.7-DEVEL and let me know if that fixes your issue. I tried it against two devices. One on the new version and one on the old and both of them reported back metrics. Once someone besides me validates it I'll cut a 1.0.7 release for realz.

**Comment by janost** [comment]
@nshttpd Thank you for the quick fix, it's working great!

**Comment by nshttpd** [comment]
did a real 1.0.7 release. Thanks @janost for verifying that the fix worked.
