### ISSUE TITLE
Docker 1.0.8 image broken

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [nshttpd/mikrotik-exporter#40]
/app/start.sh: line 8: /app/mikrotik-exporter: not found

PS: 

/app # ls -la
total 11432
drwxr-xr-x    1 root     root          4096 Jul  6 02:21 .
drwxr-xr-x    1 root     root          4096 Jul 21 16:34 ..
-rwxr-xr-x    1 root     root      11689927 Jul  6 02:20 mikrotik-exporter
-rwxr-xr-x    1 root     root           195 Jul  6 02:20 start.sh
/app # ./mikrotik-exporter
sh: ./mikrotik-exporter: not found
/app #

After some investigations i found that exist compatibily problem between your base image and executable: 

More details here : 
https://stackoverflow.com/questions/54281646/executable-in-docker-image-not-found

**Comment by nshttpd** [comment]
stupid alpine. switch to debian stretch slim as base and confirmed it works on local server.
