### ISSUE TITLE
How to use it on docker

### ISSUE THREAD

**Issue by patan32** [nshttpd/mikrotik-exporter#55]
Hello,

How do i use this in docker. I pull the latest image from docker hub. How do i use the portainer to create the image and run it. Any help will be appreciated.

**Comment by infodba0815** [comment]
Hi
thanks for the exporter. That is 100% what I am looking for ... but it would be really helpful if same more information about the setup would be available ...

**docker**
1) how to use the docker for example with portainer
- where to store the config file / volumes to create
- how to handover the config file

**prometheus server**
2) how to use the exporter in prometheus server
- how to define the target
- is http possible. Which port


Thanks a lot for the great work

**Comment by bountin** [comment]
I've got it running with the following:
```
docker run -d --name mikrotik-exporter -p 9436:9436 -e ADDRESS=192.168.1.1 -e USER=prometheus -e PASSWORD=changeme -e DEVICE=my_router nshttpd/mikrotik-exporter:1.0.11
```

**Comment by martydingo** [comment]
I wrote and currently use the following docker-compose file.
`version: "3"

services:
  prom_mikrotik_exporter:
    image: nshttpd/mikrotik-exporter:1.0.11 # Make sure to check versioning
    volumes:
      - './config:/config'
    env_file: .env
    ports:
      - 9436:9436
    restart: unless-stopped`

the .env file contents

`
CONFIG_FILE=/config/config.yml
`
and then put config.yml for the Mikrotik Exporter in <docker-compose.yml location>/config

`docker-compose up -d && docker-compose start && docker-compose logs -f`

from there you should see any errors that may need fixing, or if it's started you should be able to access http://<ip of exporter>:9436

**Comment by encryptblockr** [comment]
> CONFIG_FILE=/config/config.yml

and sample content of `config.yml`???
