### ISSUE TITLE
Multiple devices - no data due downtime of one device

### ISSUE THREAD

**Issue by s0uky** [nshttpd/mikrotik-exporter#56]
Hello,
I have 5 devices in config and if one device has downtime, prometheus can't scrape other devices too, because no metrics are exposed.

Behavior which I expecting is for example: `mikrotik_monitor_status{interface=~"ether1|ether1-gateway|WAN"}` shows me which ethernet is down/up and not no data from all devices.

**Comment by nshttpd** [comment]
Which version are you running and are there any panic error messages? I've got a device down at the moment and while the collector spits out error messages that it can't talk to it, the other devices scrape properly.

**Comment by nshttpd** [comment]
Nevermind, reproduced the issue. Let me look at it.

**Comment by nshttpd** [comment]
1.0.11 should fix this.

**Comment by addRange** [comment]
hi, same problem on mikrotik-exporter:1.0.11 and mikrotik-exporter:1.0.12-DEVEL. 
if one device down prometheus STATE go down
