### ISSUE TITLE
WithDHCPL is never used

### ISSUE THREAD

**Issue by shadowlmd** [nshttpd/mikrotik-exporter#68]
How come WithDHCPL() is never used? There is a `dhcpl` option in example config file, but it is missing from config.go, therefore, never parsed.

**Comment by nshttpd** [comment]
No idea why it's not there but thanks for noticing. PR in flight to try and fix it.

**Comment by shadowlmd** [comment]
Just noticed you have a typo in config.go:
```DHCPL   bool `yaml:"dhcpl,omitemptu"````
Should be:
```DHCPL   bool `yaml:"dhcpl,omitempty"````
