### ISSUE TITLE
Not all data types showing up in exporter

### ISSUE THREAD

**Issue by ilovepancakes95** [nshttpd/mikrotik-exporter#78]
I am using this dashboard (https://grafana.com/grafana/dashboards/10950) in Grafana with this exporter running on docker. The dashboard seems to reference DHCP data and interface status info that the exporter doesn't seem to be providing to prometheus. Is there a way to enable more data fields to export? I am running this on docker via portainer and provided environment variables for name, address, user, and password. Are there any other that control the category of info collected? Such as DHCP # of leases, etc...?

**Comment by richardbeumer** [comment]
I have the same issue. How did you fix this?

**Comment by richardbeumer** [comment]
@ilovepancakes95 I have the same issue. Do you have it fixed already?

**Comment by ilovepancakes95** [comment]
I had to enable some more "features" via the config.yml file. Below is my entire file for reference. I had to disable the IPv6 features too since they aren't being used on my network and the exporter would timeout since it couldn't find data to pull for those.

devices:
    name: [device name]
    address: [device IP]
    user: [device username]
    password: [device password]

features:
  bgp: true
  dhcp: true
  dhcpv6: false
  dhcp-leases: true
  routes: true
  routesv6: false
  pool: true
  poolv6: false
  optics: true
  wlan-interfaces: true
  wlan-stations: true
  monitor: true
  ipsec-peers: true
  ospf-neighbor: true

**Comment by richardbeumer** [comment]
@ilovepancakes95 Thnx... I got it working now. DHCP status is showing, but still now Wlan info.

**Comment by ilovepancakes95** [comment]
@richardbeumer I don't have any wlan interfaces on mine so can't test but I would look into if there are any other feature flags to add to the config file that enable more to do with wlan. Assuming you have the two in there set to true already.

**Comment by richardbeumer** [comment]
@ilovepancakes95 I did set those two both to `true`. Cannot find any more Wlan related features in code. But maybe I'm overlooking something
