### ISSUE TITLE
Question: Colection behavior with interfaces with no/zero values?

### ISSUE THREAD

**Issue by prologic** [nshttpd/mikrotik-exporter#88]
Am I correct in that interfaces with no values produced or zero values are not collected by defualt? It seems that way from observation and inspection of the code.

**Comment by nshttpd** [comment]
If it's not a Running interface the stats won't be collected.

```
	reply, err := ctx.client.Run("/interface/print", "?disabled=false", "?running=true", "=.proplist="+strings.Join(c.props, ","))

```

Is it running and just not taking any traffic at all?

**Comment by nshttpd** [comment]
I believe #105 just fixed this issue.
