### ISSUE TITLE
CAPsMAN support

### ISSUE THREAD

**Issue by jacekjaros** [nshttpd/mikrotik-exporter#89]
Hi,

first of all - thanks for mikrotik exporter - this soft make my life way easier :).

I noticed that in networks where i use CAPsMAN I'm unable to get information about WLAN (eg. mikrotik_wlan_station_signal_to_noise). Is there option to add support for CAPsMAN?

Thanks,
Jacek

**Comment by jvwag** [comment]
+1

**Comment by nshttpd** [comment]
This PR #120 this should be resolved.
