### ISSUE TITLE
expiresafter metric label has high cardinality

### ISSUE THREAD

**Issue by knyar** [nshttpd/mikrotik-exporter#93]
`mikrotik_dhcp_leases_metrics` metric has an `expiresafter` label that seems to indicate time remaining until a DHCP lease is expired. Typically Prometheus scraping intervals and DHCP lease renew times are not coordinated, which means that label values exposed to Prometheus during scraping (and written to TSDB) will often be different. This results in high [time series churn](https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality).

This illustrates the changing nature of the `expiresafter` label:
```
# for i in {1..4}; do curl -s http://localhost:9104/metrics | grep mikrotik_dhcp_leases_metrics.*MikroTik; sleep 1; done
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.6",activemacaddress="B8:69:XX:3A:XX:05",address="10.11.12.1",expiresafter="8m",hostname="MikroTik",name="homerouter",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.6",activemacaddress="B8:69:XX:3A:XX:05",address="10.11.12.1",expiresafter="7m59s",hostname="MikroTik",name="homerouter",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.6",activemacaddress="B8:69:XX:3A:XX:05",address="10.11.12.1",expiresafter="7m57s",hostname="MikroTik",name="homerouter",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.6",activemacaddress="B8:69:XX:3A:XX:05",address="10.11.12.1",expiresafter="7m56s",hostname="MikroTik",name="homerouter",status="bound"} 1
```

Note that high-cardinality labels are [explicitly discouraged](https://prometheus.io/docs/practices/naming/#labels) by Prometheus documentation, so the best course of action is probably to remove this label.

cc @bubnovd who added this metric.

**Comment by nshttpd** [comment]
Looks like this has been fixed with the latest merge that I've gotten around to merging in.

**Comment by knyar** [comment]
Note that this still seems to be happening with the latest `trunk` version. Even though label values now seem to be integers, they change very often, which would create a large number of distinct label combinations for this metric in the Prometheus server.
```
# for i in {1..4}; do curl -s http://localhost:9436/metrics | grep mikrotik_dhcp_leases_metrics | grep 10.11.12.4; sleep 1; done
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.4",activemacaddress="80:DD:9C:82:91:91",address="10.11.12.1",expiresafter="476",hostname="\"\"",name="r",server="dhcp-lan",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.4",activemacaddress="80:DD:9C:82:91:91",address="10.11.12.1",expiresafter="474",hostname="\"\"",name="r",server="dhcp-lan",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.4",activemacaddress="80:DD:9C:82:91:91",address="10.11.12.1",expiresafter="472",hostname="\"\"",name="r",server="dhcp-lan",status="bound"} 1
mikrotik_dhcp_leases_metrics{activeaddress="10.11.12.4",activemacaddress="80:DD:9C:82:91:91",address="10.11.12.1",expiresafter="470",hostname="\"\"",name="r",server="dhcp-lan",status="bound"} 1
```

Is this expected?
